# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0982750fe77137f85dadda7b8eb54859ef9608cdd96cb52654fe8003645cb71e0ad8027926bd1671b4f67d14cb0ecfcee77de1c15aa5ad05f3ea5e7410bd2b7b

test:
  secret_key_base: 51d90e46d7272f759a8e6e16c023d8da014dbd07c9a439e566f22ddc2fa0510935273fb1b722000ef47f048129d43caddba23d9f8983d9d4eee44d791d7bc63b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
